#!/bin/bash

names="t01_H2 t02_H4 t02_CH4 t03_C2H2 t04_C2H4 t05_C2H6 t06_C6H6 t07_Cn t08_CnHn t08_pentacene t08_pentacene_opt t09_pentaceneH4 t07_biphenyl Circumcoronene t10_diacetylene t10_diacetylene-CH3 t11_terephtalic t12_PTCA t13_DiselAlder t13_DieselAlder2"

bkdir=`pwd`

for d in $names; do
    echo $d
    cd $d
    rm CHARGES param.dat answer.* *.out *.log
    rm cel_.lvs answer-image.*
    cd $bkdir
done