#!/usr/bin/env python3
"""Direct linear PLQ regression on MACE-generated interaction energies.

Fits:  E_int(k) = Σ_i [ A_{el_i}·V_P(r_i^k) + B_{el_i}·V_L(r_i^k) + C_{el_i}·V_Q(r_i^k) ]
using numpy.linalg.lstsq (linear algebra, no gradient descent).

Data source: MACE z-scan generated by analyze_madsurf_dft_zscan.py
  E_int = E_MACE(slab+mol@z) − E_MACE(slab) − E_MACE(mol_vacuum)
  Ag slab fixed; molecule scanned flat at multiple z heights × lateral positions.

PLQ fields: built from CHGCAR/LOCPOT via existing pyBall infrastructure.

Produces 4 plots in dft_plq_analysis/:
  plot5_plq_parity.png         E_PLQ vs MACE E_int scatter (R², RMSE)
  plot6_plq_residuals_vs_z.png Residuals vs z — systematic = functional form limit
  plot7_three_curves.png       MACE E_int + PLQ fit vs z on same axes
  plot8_coefficients.png       Fitted A, B, C per element

Data files (printed at startup):
  EXTXYZ  : tests/tGridFFJax/mad-surf_data/full_train_test_std_config_types.extxyz
  MACE    : tests/tGridFFJax/mad-surf_data/models/full_dataset_config_weights/MACE_model.model
  CHGCAR  : /home/niel/git/ORR_HER_Ag_Colab/results/Ag_ORR_HER/slab_clean/final_scf_12x12x1/CHGCAR
  LOCPOT  : /home/niel/git/ORR_HER_Ag_Colab/results/Ag_ORR_HER/slab_clean/workfunc_12x12x1/LOCPOT

Usage:
  python3 tests/tGridFFJax/fit_plq_to_dft.py
  python3 tests/tGridFFJax/fit_plq_to_dft.py --device cuda
  python3 tests/tGridFFJax/fit_plq_to_dft.py --force-recompute-mace
  python3 tests/tGridFFJax/fit_plq_to_dft.py --no-locpot
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import time
from collections import Counter

import numpy as np

os.environ.setdefault("MPLCONFIGDIR", "/tmp/mpl_plq_fit")
import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

# ── canonical paths ──────────────────────────────────────────────────────────
HERE       = os.path.dirname(os.path.abspath(__file__))
FIRECORE   = os.path.abspath(os.path.join(HERE, "..", ".."))
EXTXYZ     = os.path.join(HERE, "mad-surf_data",
                          "full_train_test_std_config_types.extxyz")
MACE_MODEL = os.path.join(HERE, "mad-surf_data", "models",
                          "full_dataset_config_weights", "MACE_model.model")
import os as _os
# DFT slab paths come from environment (no hardcoded workstation paths).
# Set GRIDFF_JAX_CHGCAR and GRIDFF_JAX_LOCPOT in your shell.
CHGCAR     = _os.environ.get("GRIDFF_JAX_CHGCAR", "")
LOCPOT     = _os.environ.get("GRIDFF_JAX_LOCPOT", "")
MADSURF_MAIN = os.path.join(HERE, "MAD-SURF-main")
OUT_DIR    = os.path.join(HERE, "dft_plq_analysis")

for _p in [FIRECORE, MADSURF_MAIN]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

# Element set for PLQ fit (must match molecule composition)
ELEMENTS = ["C", "H", "N", "O"]
N_EL     = len(ELEMENTS)
EL_MAP   = {el: i for i, el in enumerate(ELEMENTS)}

_RE_CONFIG  = re.compile(r'config_type=(\S+)')
_RE_LATTICE = re.compile(r'Lattice="([^"]+)"')


# ════════════════════════════════════════════════════════════════════════════
# 1. Geometry reader (positions only — DFT energies never used)
# ════════════════════════════════════════════════════════════════════════════

def read_geometry_frames(extxyz_path):
    """Read first MD_interface_Ag frame; split into Ag slab + molecule.
    REF_energy is never used.
    """
    cell = None
    n_total = 0
    print(f"Reading geometry from: {extxyz_path}")
    with open(extxyz_path, "r", errors="ignore") as fh:
        while True:
            line = fh.readline()
            if not line:
                break
            line = line.strip()
            if not line:
                continue
            try:
                n_atoms = int(line)
            except ValueError:
                continue

            info      = fh.readline().rstrip("\n")
            atom_lines = [fh.readline() for _ in range(n_atoms)]
            n_total  += 1

            m = _RE_CONFIG.search(info)
            ctype = m.group(1) if m else "unknown"
            m = _RE_LATTICE.search(info)
            if m:
                vals = list(map(float, m.group(1).split()))
                cell = np.array(vals, dtype=float).reshape(3, 3)

            if ctype != "MD_interface_Ag":
                continue

            syms, pos = [], []
            ok = True
            for al in atom_lines:
                parts = al.split()
                if len(parts) < 4:
                    ok = False; break
                syms.append(parts[0])
                pos.append([float(parts[1]), float(parts[2]), float(parts[3])])
            if not ok:
                continue
            pos = np.array(pos, dtype=float)

            ag_m     = np.array([s == "Ag" for s in syms])
            ag_syms  = [s for s, m_ in zip(syms, ag_m) if m_]
            mol_syms = [s for s, m_ in zip(syms, ag_m) if not m_]
            ag_pos   = pos[ag_m]
            mol_pos  = pos[~ag_m]
            print(f"  Ag slab  : {ag_m.sum()} atoms (frame {n_total})")
            print(f"  Molecule : {len(mol_syms)} atoms {dict(Counter(mol_syms))}")
            return ag_syms, ag_pos, mol_syms, mol_pos, cell

    raise RuntimeError("No MD_interface_Ag frame found")


# ════════════════════════════════════════════════════════════════════════════
# 2. Molecule orientation
# ════════════════════════════════════════════════════════════════════════════

def orient_molecule_flat(mol_pos):
    """PCA rotation: molecular normal → z-axis. Returns flat_pos (centered)."""
    com = mol_pos.mean(axis=0)
    centered = mol_pos - com
    cov = centered.T @ centered
    _, eigenvectors = np.linalg.eigh(cov)
    R = np.column_stack([eigenvectors[:, 2], eigenvectors[:, 1], eigenvectors[:, 0]])
    flat = centered @ R
    if flat[:, 2].mean() < 0:
        flat[:, 2] *= -1
    return flat


def find_z_top_ag(ag_pos, cell):
    cell_z = float(cell[2, 2])
    return float(ag_pos[ag_pos[:, 2] < (cell_z - 1.0), 2].max())


# ════════════════════════════════════════════════════════════════════════════
# 3. MACE scan — z-scan at multiple lateral positions
# ════════════════════════════════════════════════════════════════════════════

def run_mace_scan_grid(ag_syms, ag_pos, mol_syms, mol_pos_flat,
                       cell, z_vals, lat_offsets,
                       mace_model_path, device, z_top_ag):
    """Scan molecule at multiple z heights × lateral offsets using MACE.

    lat_offsets : list of (dx, dy) Å offsets added to the atop-site position.
    Returns list of dicts, each with: z_rel, e_int, mol_pos_global, mol_syms
    """
    from mace.calculators import MACECalculator  # type: ignore
    from ase import Atoms  # type: ignore

    print(f"  MACE model : {mace_model_path}")
    calc = MACECalculator(model_paths=mace_model_path,
                          device=device, default_dtype="float64")

    # Reference Ag top position (atop site)
    cell_z  = float(cell[2, 2])
    real_m  = ag_pos[:, 2] < (cell_z - 1.0)
    top_idx = np.argmax(ag_pos[real_m][:, 2])
    atop_xy = ag_pos[real_m][top_idx, :2]
    print(f"  Atop site : ({atop_xy[0]:.3f}, {atop_xy[1]:.3f}) Å")

    # E_slab (fixed Ag, computed once)
    slab_at = Atoms(symbols=ag_syms, positions=ag_pos,
                    cell=cell, pbc=[True, True, True])
    slab_at.calc = calc
    e_slab = float(slab_at.get_potential_energy())
    print(f"  E_slab = {e_slab:.4f} eV")

    # E_mol reference: same cell + pbc as E_slab/E_comb, molecule at vacuum midpoint.
    cell_z      = float(cell[2, 2])
    z_bot_img   = cell_z - 0.5
    z_mol_ref   = (z_top_ag + z_bot_img) / 2.0
    mol_ref_pos = mol_pos_flat.copy()
    mol_ref_pos[:, 0] += atop_xy[0]
    mol_ref_pos[:, 1] += atop_xy[1]
    mol_ref_pos[:, 2] += z_mol_ref
    mol_vac = Atoms(symbols=mol_syms, positions=mol_ref_pos,
                    cell=cell, pbc=[True, True, True])
    mol_vac.calc = calc
    e_mol = float(mol_vac.get_potential_energy())
    print(f"  E_mol  = {e_mol:.4f} eV  (z_ref={z_mol_ref:.2f} Å, same cell/pbc)")

    n_ag     = len(ag_syms)
    n_total  = len(z_vals) * len(lat_offsets)
    records  = []
    t0 = time.perf_counter()
    cnt = 0

    print(f"\n  Scan: {len(z_vals)} z × {len(lat_offsets)} lateral = {n_total} points")
    for dx, dy in lat_offsets:
        lat_xy = atop_xy + np.array([dx, dy])
        for z_rel in z_vals:
            mol_z = mol_pos_flat.copy()
            mol_z[:, 0] += lat_xy[0]
            mol_z[:, 1] += lat_xy[1]
            mol_z[:, 2] += z_top_ag + z_rel

            comb = Atoms(symbols=ag_syms + mol_syms,
                         positions=np.vstack([ag_pos, mol_z]),
                         cell=cell, pbc=[True, True, True])
            comb.calc = calc
            e_int = float(comb.get_potential_energy()) - e_slab - e_mol
            records.append({
                "z_rel":      z_rel,
                "e_int":      e_int,
                "mol_pos":    mol_z.copy(),
                "mol_syms":   mol_syms,
                "lat_offset": (dx, dy),
            })
            cnt += 1
            if cnt % 20 == 0 or cnt == n_total:
                print(f"    [{cnt}/{n_total}] z={z_rel:.2f}Å  "
                      f"E_int={e_int*1000:+7.1f} meV  "
                      f"{time.perf_counter()-t0:.0f}s")

    print(f"  Grid scan done in {time.perf_counter()-t0:.1f}s")
    return records, {"e_slab": e_slab, "e_mol": e_mol, "atop_xy": atop_xy}


# ════════════════════════════════════════════════════════════════════════════
# 4. PLQ field builder
# ════════════════════════════════════════════════════════════════════════════

def build_plq_fields(chgcar_path, locpot_path, out_dir):
    """Build (or load cached) PLQ B-spline coefficient grids.

    Returns
    -------
    coeffs : (nz, ny, nx, 3)  [P, L, Q] stacked
    meta   : dict with cell, origin, voxel, grid_xyz, z_ref
    """
    cache_c = os.path.join(out_dir, "_Bspline_PLQ_coeffs.npy")
    cache_m = os.path.join(out_dir, "_Bspline_PLQ_meta.npy")

    if os.path.exists(cache_c) and os.path.exists(cache_m):
        print(f"  Loading cached PLQ : {cache_c}")
        coeffs = np.load(cache_c)
        meta   = np.load(cache_m, allow_pickle=True).item()
        return coeffs, meta

    from pyBall.gridff_jax.config import DensityBackendConfig, GridConfig, FeatureToggles
    from pyBall.gridff_jax.density_backends.vasp_volumetric import VaspVolumetricBackend
    from pyBall.gridff_jax.substrate_fields import build_substrate_grids

    print(f"  CHGCAR : {chgcar_path}")
    print(f"  LOCPOT : {locpot_path}")

    backend_cfg = DensityBackendConfig(kind="vasp_volumetric",
                                       chgcar_path=chgcar_path,
                                       locpot_path=locpot_path)
    density  = VaspVolumetricBackend(backend_cfg).load()
    gc       = GridConfig(builder_mode="metal_density_plq")
    mol_elements = tuple(sorted(set(ELEMENTS)))

    print(f"  Grid shape xyz = {density.grid_shape_xyz}")
    t0 = time.perf_counter()
    grids = build_substrate_grids(density, reactive_elements=mol_elements,
                                  grid_config=gc, toggles=FeatureToggles(),
                                  prefer_jax=False)
    print(f"  B-spline built in {time.perf_counter()-t0:.1f}s")

    coeffs = np.stack([grids["pauli_coeff_zyx"],
                       grids["london_coeff_zyx"],
                       grids["coulomb_coeff_zyx"]], axis=-1)
    meta   = {"cell":     density.cell,
              "origin":   density.origin,
              "voxel":    density.voxel,
              "grid_xyz": density.grid_shape_xyz,
              "z_ref":    grids["metadata"]["z_ref"]}
    np.save(cache_c, coeffs)
    np.save(cache_m, meta)  # type: ignore[arg-type]
    print(f"  Cached → {cache_c}")
    return coeffs, meta


# ════════════════════════════════════════════════════════════════════════════
# 5. PLQ sampling
# ════════════════════════════════════════════════════════════════════════════

def sample_plq_at_positions(coeffs, meta, positions):
    """Cubic B-spline evaluation at Cartesian positions (N,3) → (N,3) [P,L,Q]."""
    from pyBall.gridff_jax.hybrid_energy.model import _sample_bspline_numpy
    from pyBall.gridff_jax.interfaces import DensityData

    density_stub = DensityData(
        cell=np.asarray(meta["cell"], dtype=float),
        origin=np.asarray(meta["origin"], dtype=float),
        voxel=meta["voxel"],
        symbols=[],
        positions=np.zeros((0, 3), dtype=float),
        charges=None,
        rho_zyx=None,
        v_loc_zyx=None,
        grid_shape_xyz_hint=meta["grid_xyz"],
    )
    result = _sample_bspline_numpy(coeffs, density_stub, positions)
    if result.ndim == 1:
        result = result[:, None]
    return result   # (N, 3)


def map_to_plq_cell(mol_pos, z_top_md, meta):
    """Shift z to align surface reference; fold x,y into PLQ cell via PBC.

    z-shift : z_top_md → meta['z_ref']
    x,y fold: fractional coordinates mod 1.0 in the 2D PLQ cell
    """
    plq_cell = np.asarray(meta["cell"], dtype=float)
    pos = mol_pos.copy().astype(float)

    # z-shift: align Ag top layer with PLQ reference height
    pos[:, 2] += float(meta["z_ref"]) - z_top_md

    # x,y fold into PLQ cell (non-orthogonal PBC)
    a1 = plq_cell[0, :2]
    a2 = plq_cell[1, :2]
    M  = np.stack([a1, a2], axis=1)        # (2,2)
    Minv = np.linalg.inv(M)
    frac = (Minv @ pos[:, :2].T).T         # fractional x,y
    frac = frac % 1.0
    pos[:, :2] = (M @ frac.T).T
    return pos


# ════════════════════════════════════════════════════════════════════════════
# 6. Linear regression
# ════════════════════════════════════════════════════════════════════════════

def build_design_matrix(records, coeffs, meta, z_top_md):
    """Build design matrix X[n, 3*N_EL] and target vector y[n].

    X[k, 0*N_EL + el] = Σ V_P(r_i)  for atoms of element el in config k
    X[k, 1*N_EL + el] = Σ V_L(r_i)
    X[k, 2*N_EL + el] = Σ V_Q(r_i)
    """
    n   = len(records)
    X   = np.zeros((n, 3 * N_EL), dtype=float)
    y   = np.zeros(n,              dtype=float)

    for k, rec in enumerate(records):
        y[k] = rec["e_int"]
        mol_pos_plq = map_to_plq_cell(rec["mol_pos"], z_top_md, meta)
        plq = sample_plq_at_positions(coeffs, meta, mol_pos_plq)  # (N_mol, 3)
        for i, sym in enumerate(rec["mol_syms"]):
            el = EL_MAP.get(sym, -1)
            if el < 0:
                continue
            X[k, 0 * N_EL + el] += plq[i, 0]   # Pauli
            X[k, 1 * N_EL + el] += plq[i, 1]   # London
            X[k, 2 * N_EL + el] += plq[i, 2]   # Coulomb

        if (k + 1) % 50 == 0 or (k + 1) == n:
            print(f"    design matrix: {k+1}/{n}")

    return X, y


def solve_plq(X, y):
    """Least-squares fit θ such that X θ ≈ y."""
    theta, residuals, rank, sv = np.linalg.lstsq(X, y, rcond=None)
    y_pred = X @ theta
    rmse   = float(np.sqrt(np.mean((y_pred - y)**2)))
    ss_res = float(np.sum((y_pred - y)**2))
    ss_tot = float(np.sum((y - y.mean())**2))
    r2     = float(1.0 - ss_res / max(ss_tot, 1e-30))
    return theta, y_pred, rmse, r2, rank


def print_theta_table(theta, mol_syms):
    """Print fitted PLQ coefficients A, B, C per element."""
    els_present = sorted(set(mol_syms) & set(ELEMENTS))
    print("\n  Fitted PLQ coefficients (eV / field_unit):")
    print(f"  {'Element':>8}  {'A (Pauli)':>14}  {'B (London)':>14}  {'C (Coulomb)':>14}")
    for el in els_present:
        i = EL_MAP[el]
        A = theta[0 * N_EL + i]
        B = theta[1 * N_EL + i]
        C = theta[2 * N_EL + i]
        print(f"  {el:>8}  {A:>14.6f}  {B:>14.6f}  {C:>14.6f}")


# ════════════════════════════════════════════════════════════════════════════
# 7. Plots
# ════════════════════════════════════════════════════════════════════════════

def _save(fig, path):
    fig.savefig(path, dpi=130, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved : {path}")


def plot5_parity(y_mace, y_plq, out_dir):
    ym = np.asarray(y_mace) * 1000   # meV
    yp = np.asarray(y_plq)  * 1000
    rmse = float(np.sqrt(np.mean((yp - ym)**2)))
    ss_res = float(np.sum((yp - ym)**2))
    r2   = float(1.0 - ss_res / max(float(np.var(ym) * len(ym)), 1e-30))
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.scatter(ym, yp, s=15, alpha=0.6, color="steelblue")
    lim = [min(ym.min(), yp.min()) - 20, max(ym.max(), yp.max()) + 20]
    ax.plot(lim, lim, "k--", lw=1, label="perfect")
    ax.set_xlim(*lim); ax.set_ylim(*lim)
    ax.set_xlabel("MACE E_int (meV)")
    ax.set_ylabel("E_PLQ fitted (meV)")
    ax.set_title(f"PLQ linear fit vs MACE\nRMSE = {rmse:.1f} meV   R² = {r2:.4f}   N = {len(ym)}")
    ax.legend(); ax.grid(True, alpha=0.25)
    _save(fig, os.path.join(out_dir, "plot5_plq_parity.png"))


def plot6_residuals(z_rel, y_mace, y_plq, out_dir):
    idx = np.argsort(z_rel)
    z   = np.asarray(z_rel)[idx]
    res = (np.asarray(y_plq)[idx] - np.asarray(y_mace)[idx]) * 1000
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.scatter(z, res, s=15, color="crimson", alpha=0.7, rasterized=True)
    ax.axhline(0, color="k", lw=0.5, ls="--")
    ax.set_xlabel("z above Ag top layer (Å)")
    ax.set_ylabel("E_PLQ − E_MACE (meV)")
    ax.set_title("PLQ residuals vs height\n"
                 "Systematic patterns → functional form limitation of PLQ\n"
                 f"CHGCAR: {CHGCAR}")
    ax.grid(True, alpha=0.25)
    _save(fig, os.path.join(out_dir, "plot6_plq_residuals_vs_z.png"))


def plot7_curves(z_rel, y_mace, y_plq, out_dir):
    idx = np.argsort(z_rel)
    z   = np.asarray(z_rel)[idx]
    ym  = np.asarray(y_mace)[idx] * 1000
    yp  = np.asarray(y_plq)[idx]  * 1000
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(z, ym, "b-o", ms=3, lw=1.5, label="MACE E_int (target)")
    ax.plot(z, yp, "r-",  lw=2,          label="PLQ fit (optimal)")
    ax.axhline(0, color="k", lw=0.5, ls="--")
    ax.set_xlabel("z above Ag top layer (Å)")
    ax.set_ylabel("E_int (meV)")
    ax.set_title(f"MACE interaction energy vs optimal PLQ fit\n"
                 f"MACE: {MACE_MODEL}\n"
                 f"CHGCAR: {CHGCAR}")
    ax.legend(); ax.grid(True, alpha=0.25)
    _save(fig, os.path.join(out_dir, "plot7_three_curves.png"))


def plot8_coefficients(theta, mol_syms, out_dir):
    els = sorted(set(mol_syms) & set(ELEMENTS))
    field_names = ["Pauli (A)", "London (B)", "Coulomb (C)"]
    colors      = ["#e41a1c", "#377eb8", "#4daf4a"]
    x = np.arange(len(els))
    width = 0.25

    fig, ax = plt.subplots(figsize=(8, 5))
    for j, (fname, col) in enumerate(zip(field_names, colors)):
        vals = [theta[j * N_EL + EL_MAP[el]] for el in els]
        ax.bar(x + j * width, vals, width, label=fname, color=col, alpha=0.8)

    ax.set_xticks(x + width)
    ax.set_xticklabels(els)
    ax.set_xlabel("Element")
    ax.set_ylabel("Coefficient (eV / field_unit)")
    ax.set_title("Optimal PLQ coefficients per element\n"
                 "(fitted by linear least squares to MACE E_int)")
    ax.legend(); ax.grid(True, alpha=0.2, axis="y")
    ax.axhline(0, color="k", lw=0.5)
    _save(fig, os.path.join(out_dir, "plot8_coefficients.png"))


# ════════════════════════════════════════════════════════════════════════════
# 8. Main
# ════════════════════════════════════════════════════════════════════════════

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--z-min",   type=float, default=1.5)
    p.add_argument("--z-max",   type=float, default=8.0)
    p.add_argument("--z-step",  type=float, default=0.2,
                   help="z step Å (default 0.2 → ~33 z points)")
    p.add_argument("--device",  default="cpu")
    p.add_argument("--no-locpot", action="store_true")
    p.add_argument("--force-recompute-mace",  action="store_true")
    p.add_argument("--force-recompute-plq",   action="store_true")
    args = p.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    scan_cache  = os.path.join(OUT_DIR, "_mace_scan_grid_cache.npy")
    coeffs_cache = os.path.join(OUT_DIR, "_Bspline_PLQ_coeffs.npy")

    print("=" * 64)
    print("PLQ linear regression on MACE interaction energies")
    print(f"  EXTXYZ  : {EXTXYZ}")
    print(f"  MACE    : {MACE_MODEL}")
    print(f"  CHGCAR  : {CHGCAR}")
    print(f"  LOCPOT  : {LOCPOT if not args.no_locpot else '[disabled]'}")
    print(f"  Out dir : {OUT_DIR}")
    print("=" * 64)

    # ── MACE scan ──────────────────────────────────────────────────────────
    if os.path.exists(scan_cache) and not args.force_recompute_mace:
        print(f"\nLoading cached MACE scan: {scan_cache}")
        cache_obj = np.load(scan_cache, allow_pickle=True).item()
        records   = cache_obj["records"]
        mace_meta = cache_obj["mace_meta"]
        ag_pos    = cache_obj["ag_pos"]
        cell      = cache_obj["cell"]
        mol_syms  = cache_obj["mol_syms"]
        z_top_md  = float(cache_obj["z_top_md"])
        print(f"  {len(records)} scan points loaded")
    else:
        print("\nReading geometry...")
        ag_syms, ag_pos, mol_syms, mol_pos, cell = read_geometry_frames(EXTXYZ)
        mol_pos_flat = orient_molecule_flat(mol_pos)
        z_top_md = find_z_top_ag(ag_pos, cell)
        print(f"  z_top_ag = {z_top_md:.4f} Å")

        z_vals = np.arange(args.z_min, args.z_max + args.z_step / 2, args.z_step)

        # Lateral offsets: atop site + 3 displaced positions for variety
        # Offsets in Å relative to atop site; use Ag NN distance ≈ 2.89 Å
        nn = 2.89
        lat_offsets = [
            (0.0,          0.0),         # atop
            (nn / 2,       0.0),         # bridge
            (0.0,          nn / 2),      # bridge (y)
            (nn / 3,       nn / 3),      # near hollow
        ]
        print(f"\nRunning MACE grid scan ({len(z_vals)} z × {len(lat_offsets)} lateral)...")
        records, mace_meta = run_mace_scan_grid(
            ag_syms, ag_pos, mol_syms, mol_pos_flat,
            cell, z_vals, lat_offsets,
            MACE_MODEL, args.device, z_top_md)

        cache_obj = {"records": records, "mace_meta": mace_meta,
                     "ag_pos": ag_pos, "cell": cell,
                     "mol_syms": mol_syms, "z_top_md": z_top_md}
        np.save(scan_cache, cache_obj, allow_pickle=True)  # type: ignore[arg-type]
        print(f"  Cached MACE scan → {scan_cache}")

    # Print MACE scan statistics
    z_all  = np.array([r["z_rel"]  for r in records])
    ei_all = np.array([r["e_int"]  for r in records])
    print(f"\nMACE scan stats:")
    print(f"  N points    : {len(records)}")
    print(f"  z range     : {z_all.min():.2f} → {z_all.max():.2f} Å")
    print(f"  E_int range : {ei_all.min()*1000:.1f} → {ei_all.max()*1000:.1f} meV")
    print(f"  E_slab      : {mace_meta['e_slab']:.4f} eV")
    print(f"  E_mol       : {mace_meta['e_mol']:.4f} eV")

    # ── PLQ fields ─────────────────────────────────────────────────────────
    print("\nBuilding PLQ fields...")
    locpot_path = None if args.no_locpot else LOCPOT
    coeffs, meta = build_plq_fields(CHGCAR, locpot_path, OUT_DIR)
    print(f"  PLQ coeffs shape : {coeffs.shape}")
    print(f"  PLQ cell         : {meta['cell']}")
    print(f"  PLQ z_ref        : {meta['z_ref']:.4f} Å")

    # ── Design matrix ──────────────────────────────────────────────────────
    print("\nBuilding design matrix X...")
    X, y = build_design_matrix(records, coeffs, meta, z_top_md)
    print(f"  X shape : {X.shape}  (N_configs × 3×N_elements)")
    print(f"  Matrix rank (estimated) : {np.linalg.matrix_rank(X)}")

    # ── Linear regression ──────────────────────────────────────────────────
    print("\nSolving least-squares...")
    theta, y_pred, rmse, r2, rank = solve_plq(X, y)
    print(f"\n  RMSE  = {rmse*1000:.2f} meV")
    print(f"  R²    = {r2:.5f}")
    print(f"  Rank  = {rank} / {X.shape[1]}")
    print_theta_table(theta, mol_syms)

    # ── Residual analysis ──────────────────────────────────────────────────
    # Subset to z-only scan (atop site, lat_offset=(0,0)) for clear 1D plots
    z_scan_mask = np.array([r.get("lat_offset") == (0.0, 0.0) for r in records])
    if z_scan_mask.sum() > 5:
        z_1d  = z_all[z_scan_mask]
        ym_1d = ei_all[z_scan_mask]
        yp_1d = y_pred[z_scan_mask]
        print(f"\n1D z-scan (atop site): {z_scan_mask.sum()} points "
              f"RMSE = {np.sqrt(np.mean((yp_1d-ym_1d)**2))*1000:.2f} meV")
    else:
        z_1d = z_all; ym_1d = y; yp_1d = y_pred  # fallback

    # ── Plots ──────────────────────────────────────────────────────────────
    print("\nGenerating plots...")
    plot5_parity(y, y_pred, OUT_DIR)
    plot6_residuals(z_all, y, y_pred, OUT_DIR)
    plot7_curves(z_1d, ym_1d, yp_1d, OUT_DIR)
    plot8_coefficients(theta, mol_syms, OUT_DIR)
    print(f"\nAll plots in {OUT_DIR}/")


if __name__ == "__main__":
    main()
