#!/usr/bin/env python3
"""Fit transferable parameters from 6D reference datasets.

Loads 6D datasets generated by ``run_6d_sampling.py``, optionally merges
multiple molecules for joint fitting, performs stratified train/val/test
splitting, and fits parameters using the existing HybridGridFFModel + optimizer.

Usage
-----
    # Single molecule:
    python run_6d_fit.py --dataset-dir datasets_6d/ --molecules CHONH2

    # Multi-molecule joint fit for transferability:
    python run_6d_fit.py --dataset-dir datasets_6d/ --molecules H,CO,H2O,CHONH2

    # Custom training settings:
    python run_6d_fit.py --dataset-dir datasets_6d/ --molecules CHONH2 \
        --max-steps 800 --learning-rate 0.005 --force-weight 15.0
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.append(str(ROOT))

from pyBall.gridff_jax import RunConfig, load_config, save_config
from pyBall.gridff_jax.atom_types import AtomTypeRegistry, save_element_pair_params
from pyBall.gridff_jax.density_backends import make_density_backend
from pyBall.gridff_jax.fit import fit_hybrid_parameters, fit_two_stage_c6
from pyBall.gridff_jax.fit.fit_6d import (
    load_6d_dataset,
    merge_datasets,
    split_6d_dataset,
)
from pyBall.gridff_jax.hybrid_energy import HybridGridFFModel
from pyBall.gridff_jax.utils import ensure_dir, save_json


def parse_args():
    p = argparse.ArgumentParser(
        description="Fit transferable parameters from 6D reference datasets",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--dataset-dir", required=True,
                   help="Directory containing *_6d.npz files from run_6d_sampling.py")
    p.add_argument("--molecules", default="CHONH2",
                   help="Comma-separated molecule names to include in fitting")
    p.add_argument("--out-dir", default=None,
                   help="Output directory (default: dataset-dir/fit_results/)")

    # Training
    p.add_argument("--max-steps", type=int, default=600, help="Optimizer steps")
    p.add_argument("--learning-rate", type=float, default=1.0e-2, help="Learning rate")
    p.add_argument("--force-weight", type=float, default=10.0, help="Force loss weight")
    p.add_argument("--val-fraction", type=float, default=0.1, help="Validation fraction")
    p.add_argument("--test-fraction", type=float, default=0.1, help="Test fraction")

    # Two-stage C6
    p.add_argument("--two-stage-c6", action="store_true",
                   help="Enable two-stage REQ -> C6 optimization")
    p.add_argument("--raw-r6", action="store_true",
                   help="Use raw 1/r^6 basis for Stage 2")
    p.add_argument("--stage2-max-steps", type=int, default=400)
    p.add_argument("--stage2-lr", type=float, default=5.0e-3)

    # Model
    p.add_argument("--prefer-jax", dest="prefer_jax", action="store_true", default=True)
    p.add_argument("--no-prefer-jax", dest="prefer_jax", action="store_false")
    p.add_argument("--use-req-plq", action="store_true",
                   help="Use REQ-coupled PLQ instead of direct pauli/london scalars")

    # Substrate (needed to rebuild model)
    p.add_argument("--substrate", default="Ag", help="Substrate element")
    p.add_argument("--seed", type=int, default=42, help="Random seed for splitting")

    return p.parse_args()


def main():
    args = parse_args()

    dataset_dir = Path(args.dataset_dir)
    out_dir = Path(args.out_dir) if args.out_dir else dataset_dir / "fit_results"
    ensure_dir(out_dir)

    mol_names = [n.strip() for n in args.molecules.split(",") if n.strip()]

    print("=" * 60)
    print("  6D Parameter Fitting")
    print("=" * 60)
    print(f"  Molecules: {mol_names}")
    print(f"  Dataset dir: {dataset_dir}")
    print(f"  Output dir: {out_dir}")

    # --- Load datasets ---
    datasets = []
    for name in mol_names:
        npz_path = dataset_dir / f"{name}_6d.npz"
        if not npz_path.exists():
            print(f"  WARNING: {npz_path} not found, skipping {name}")
            continue
        print(f"  Loading {name} ... ", end="", flush=True)
        ds = load_6d_dataset(npz_path)
        print(f"{ds.n_poses} poses, E range [{ds.energies.min()*1000:.1f}, {ds.energies.max()*1000:.1f}] meV")
        datasets.append(ds)

    if not datasets:
        print("ERROR: No datasets found. Run run_6d_sampling.py first.")
        sys.exit(1)

    # --- Merge for joint fitting ---
    if len(datasets) > 1:
        print(f"\n  Merging {len(datasets)} datasets for joint fitting ...")
        merged = merge_datasets(datasets)
        print(f"  Merged: {merged.n_poses} total poses")
    else:
        merged = datasets[0]

    # --- Stratified split ---
    print(f"\n  Splitting: val={args.val_fraction:.0%}, test={args.test_fraction:.0%}")
    split = split_6d_dataset(
        merged,
        val_fraction=args.val_fraction,
        test_fraction=args.test_fraction,
        seed=args.seed,
    )
    print(f"  Train: {split.train.n_poses}, Val: {split.val.n_poses}, Test: {split.test.n_poses}")

    # --- Load config and rebuild model ---
    config_path = dataset_dir / "config.json"
    if config_path.exists():
        config = load_config(config_path)
    else:
        config = RunConfig()
        config.surface.metal = args.substrate

    config.training.max_steps = args.max_steps
    config.training.learning_rate = args.learning_rate
    config.training.force_weight = args.force_weight
    config.training.two_stage_c6 = args.two_stage_c6
    config.training.stage2_max_steps = args.stage2_max_steps
    config.training.stage2_learning_rate = args.stage2_lr
    if args.use_req_plq:
        config.hybrid_model.use_req_plq = True
        config.training.fit_req_radius_offset = True
        config.training.fit_req_energy_scale = True
    if args.two_stage_c6:
        config.training.fit_c6_coeff = True

    print("\n[fit] Loading density ...", flush=True)
    density = make_density_backend(
        config.density_backend, surface=config.surface, grid=config.grid
    ).load()

    all_elements = sorted(set(
        sym for ds in datasets for sym in ds.adsorbate.symbols
    ))
    print(f"[fit] Elements: {all_elements}")

    print("[fit] Building model ...", flush=True)
    model = HybridGridFFModel(
        density=density,
        reactive_elements=tuple(all_elements),
        toggles=config.toggles,
        grid_config=config.grid,
        hybrid_config=config.hybrid_model,
        prefer_jax=args.prefer_jax,
    )
    if args.raw_r6 or args.two_stage_c6:
        print("[fit] Installing raw 1/r^6 dispersion grid ...", flush=True)
        model.install_raw_r6_grid()

    # --- Fit ---
    train_datasets = [(split.train.poses, split.train.teacher)]
    val_datasets = [(split.val.poses, split.val.teacher)]

    print(f"\n[fit] Starting parameter optimization ({args.max_steps} steps) ...", flush=True)
    t0 = time.perf_counter()

    if args.two_stage_c6:
        fit_result = fit_two_stage_c6(
            density=density,
            datasets=train_datasets,
            model=model,
            training=config.training,
        )
    else:
        fit_result = fit_hybrid_parameters(
            density=density,
            datasets=train_datasets,
            model=model,
            training=config.training,
        )

    t_fit = time.perf_counter() - t0
    print(f"[fit] Fitting done in {t_fit:.1f}s")

    # --- Evaluate on test set ---
    print("\n[fit] Evaluating on test set ...", flush=True)
    test_eval = model.evaluate_batch(
        split.test.poses, params=fit_result.params, compute_forces=True,
    )
    test_e_pred = np.asarray(test_eval.energies, dtype=float)
    test_e_ref = split.test.energies
    test_e_err = (test_e_pred - test_e_ref) * 1000.0

    test_rmse = float(np.sqrt(np.mean(test_e_err ** 2)))
    test_mae = float(np.mean(np.abs(test_e_err)))

    if test_eval.forces is not None:
        test_f_pred = np.asarray(test_eval.forces, dtype=float)
        test_f_ref = split.test.forces
        test_f_err = test_f_pred - test_f_ref
        test_f_rmse = float(np.sqrt(np.mean(test_f_err ** 2)))
        test_f_mae = float(np.mean(np.abs(test_f_err)))
    else:
        test_f_rmse = float("nan")
        test_f_mae = float("nan")

    print(f"\n  Test energy RMSE = {test_rmse:.1f} meV, MAE = {test_mae:.1f} meV")
    print(f"  Test force  RMSE = {test_f_rmse:.4f} eV/A, MAE = {test_f_mae:.4f} eV/A")

    # --- Save results ---
    from dataclasses import asdict
    params_dict = asdict(fit_result.params)
    save_json(params_dict, out_dir / "fit_params.json")
    save_config(config, out_dir / "config.json")

    # Save as transferable element-pair params
    registry = AtomTypeRegistry(substrate=args.substrate)
    registry.from_hybrid_params(fit_result.params, elements=all_elements)
    save_element_pair_params(registry, out_dir / f"element_pairs_{args.substrate}.json")

    metrics = {
        "molecules": mol_names,
        "substrate": args.substrate,
        "n_train": split.train.n_poses,
        "n_val": split.val.n_poses,
        "n_test": split.test.n_poses,
        "test_energy_rmse_meV": test_rmse,
        "test_energy_mae_meV": test_mae,
        "test_force_rmse_eV_A": test_f_rmse,
        "test_force_mae_eV_A": test_f_mae,
        "fit_time_seconds": t_fit,
        "training_history_length": len(fit_result.history),
    }
    save_json(metrics, out_dir / "fit_metrics.json")

    # Save split indices for reproducibility
    np.savez_compressed(
        out_dir / "split_indices.npz",
        train=split.split_indices["train"],
        val=split.split_indices["val"],
        test=split.split_indices["test"],
    )

    print(f"\n{'='*60}")
    print(f"  6D fitting complete")
    print(f"  Test RMSE: {test_rmse:.1f} meV (energy), {test_f_rmse:.4f} eV/A (force)")
    print(f"  Results saved to: {out_dir}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
