#!/usr/bin/env python
"""
Example: Plot molecular orbitals from DFTB+ using waveplot

This demonstrates how to:
1. Run DFTB+ with eigenvector output
2. Use waveplot to generate cube files
3. Read and visualize molecular orbitals
"""

import sys
sys.path.insert(0, '/home/prokophapala/git/FireCore')

import argparse
import subprocess
import os
from pathlib import Path
from ase import Atoms
from ase.io import read

from pyBall import dftb_utils as dftbu
from pyBall import plotUtils
from pyBall.AtomicSystem import AtomicSystem


def load_molecule_xyz(filename, use_ase=True):
    """Load molecule from XYZ file using ASE or AtomicSystem."""
    if use_ase:
        atoms = read(filename)
        return atoms
    else:
        mol = AtomicSystem(fname=filename)
        atoms = Atoms(
            symbols=mol.enames,
            positions=mol.apos,
            cell=mol.lvec if mol.lvec is not None else None,
            pbc=(mol.lvec is not None)
        )
        return atoms

def main():
    parser = argparse.ArgumentParser( description='Plot molecular orbitals from DFTB+ using waveplot'  )
    parser.add_argument('--molecule',type=str,  help='XYZ file to load (short names: H2O, PTCDA; or full path to .xyz file)' )
    parser.add_argument('--use-ase', action='store_true',help='Use ASE to load XYZ file (default: AtomicSystem)' )
    parser.add_argument( '--sk-path', type=str, default='/home/prokophapala/SIMULATIONS/dftbplus/slakos/3ob-3-1/', help='Path to Slater-Koster files (default: /home/prokophapala/SIMULATIONS/dftbplus/slakos/3ob-3-1/)' )
    parser.add_argument('--waveplot-exe', type=str,default='waveplot',help='Path to waveplot executable (default: waveplot)' )
    parser.add_argument('--sk-wfc-path', type=str,default='/home/prokophapala/SIMULATIONS/dftbplus/recipes/defect/carbon2d-elec/data/wfc.mio-0-1.hsd',help='Path to wavefunction coefficient file (default: /home/prokophapala/SIMULATIONS/dftbplus/recipes/defect/carbon2d-elec/data/wfc.mio-0-1.hsd)')
    parser.add_argument('--plotted-levels', type=str, default='1:-1', help='Which orbitals to plot (default: 1:-1 for all)')
    parser.add_argument('--n-points', type=int, nargs=3, default=[50, 50, 50], help='Grid resolution (nx ny nz, default: 50 50 50)')
    parser.add_argument('--workdir', type=str, default='orbital_calc', help='Working directory (default: orbital_calc)')
    parser.add_argument('--skip-dftb', action='store_true', help='Skip DFTB+ calculation (use existing detailed.xml and eigenvec.bin)')
    parser.add_argument('--skip-waveplot', action='store_true', help='Skip waveplot (use if WFC files not available)')
    parser.add_argument('--plot-2d', action='store_true', help='Plot orbitals as 2D projections after waveplot')
    parser.add_argument('--plane', type=str, default='xy', choices=['xy', 'xz', 'yz'], help='Projection plane (default: xy)')
    parser.add_argument('--orbital', type=str, default='all', help='Which orbitals to plot: "all", "occupied", "virtual", or comma-separated indices')
    parser.add_argument('--output-dir', type=str, default='orbital_plots', help='Output directory for PNG plots')
    parser.add_argument('--electrostatic', action='store_true', help='Calculate and plot electrostatic potential')
    parser.add_argument('--plot-density', action='store_true', help='Plot electron density (already generated by default)')
    parser.add_argument('--points', type=str, help='File with points (x y z per line) or comma-separated coordinates')
    parser.add_argument('--grid-points', type=int, nargs=2, default=[20, 20], help='Grid resolution for point sampling (nx ny, default: 20 20)')
    args = parser.parse_args()
    
    print("=== DFTB+ Molecular Orbital Plotting Example ===\n")
    
    # Load molecule
    if args.molecule:
        # Check if it's a short name like "H2O" or "PTCDA"
        short_names = {
            'H2O': '/home/prokophapala/git/FireCore/cpp/common_resources/xyz/H2O.xyz',
            'PTCDA': '/home/prokophapala/git/FireCore/cpp/common_resources/xyz/PTCDA.xyz'
        }
        if args.molecule in short_names:
            molecule_path = short_names[args.molecule]
            print(f"Loading {args.molecule} from: {molecule_path}")
        elif args.molecule.endswith('.xyz'):
            molecule_path = args.molecule
            print(f"Loading molecule from: {molecule_path}")
        else:
            # Try to find in common_resources
            molecule_path = f'/home/prokophapala/git/FireCore/cpp/common_resources/xyz/{args.molecule}.xyz'
            if os.path.exists(molecule_path):
                print(f"Loading {args.molecule} from: {molecule_path}")
            else:
                molecule_path = args.molecule
                print(f"Loading molecule from: {molecule_path}")
        
        atoms = dftbu.load_molecule(molecule_path, use_ase=args.use_ase)
    else:
        print("Using built-in H2O molecule")
        atoms = Atoms('H2O', positions=[
            [0.0, 0.0, 0.0],
            [0.957, 0.0, 0.0],
            [-0.240, 0.927, 0.0]
        ])
    
    print(f"System: {len(atoms)} atoms")
    print(f"Formula: {atoms.get_chemical_formula()}")
    print()
    
    # Create working directory
    workdir = Path(args.workdir).absolute()
    workdir.mkdir(exist_ok=True, parents=True)
    os.chdir(workdir)
    
    # Write XYZ file
    from pyBall import atomicUtils as au
    au.saveXYZ(es=atoms.get_chemical_symbols(), xyzs=atoms.positions, fname="geo.xyz")
    
    if not args.skip_dftb:
        # Write DFTB+ input with eigenvector output
        print("Writing DFTB+ input file...")
        dftbu.write_dftb_input_orbitals(atoms.get_chemical_symbols(), gname="geo.xyz", fname='dftb_in.hsd', basis_path=args.sk_path)
        
        # Run DFTB+
        print("Running DFTB+ calculation...")
        result = subprocess.run(['dftb+'], capture_output=True, text=True)
        
        if result.returncode != 0:
            print("DFTB+ failed!")
            print("STDERR:", result.stderr)
            print("STDOUT:", result.stdout)
            return
        
        print("DFTB+ calculation complete")
        print()
    
    # Check for required files
    if not os.path.exists('detailed.xml'):
        print("Error: detailed.xml not found!")
        print("Run DFTB+ with Options { WriteDetailedXml = Yes }")
        return
    
    if not os.path.exists('eigenvec.bin'):
        print("Error: eigenvec.bin not found!")
        print("Run DFTB+ with Analysis { WriteEigenvectors = Yes }")
        return
    
    # Run waveplot
    if not args.skip_waveplot:
        print("Running waveplot to generate cube files...")
        nx, ny, nz = args.n_points
        
        try:
            cubes = dftbu.run_waveplot( workdir='.',waveplot_exe=args.waveplot_exe,  sk_wfc_path=args.sk_wfc_path, plotted_levels=args.plotted_levels, n_points=(nx, ny, nz),  resolution=0.01,  electrostatic_potential=args.electrostatic )
            print(f"Generated {len(cubes)} cube files:")
            for cube in cubes:
                print(f"  {cube}")
            print()
        except RuntimeError as e:
            print(f"Waveplot failed: {e}")
            print()
            print("Note: waveplot requires wavefunction coefficient files (wfc.*.hsd)")
            print("These are typically in the Slater-Koster directory or a separate wfc directory")
            print("Use --skip-waveplot to skip this step")
            return
    else:
        print("Skipping waveplot (--skip-waveplot specified)")
        cubes = []
        print()
    
    # Read and display cube file info
    if cubes:
        print("Reading cube files...")
        for cube_file in cubes[:3]:  # Show first 3
            try:
                data, atoms_cube = dftbu.read_cube(cube_file)
                print(f"  {cube_file}: grid shape {data.shape}")
            except Exception as e:
                print(f"  {cube_file}: error reading - {e}")
        print()
        
        # Plot 2D projections if requested
        if args.plot_2d:
            print("Plotting 2D orbital projections...")
            output_dir = Path(args.output_dir); output_dir.mkdir(exist_ok=True, parents=True)
            for cube_file in cubes:
                output_file = output_dir / f"{Path(cube_file).stem}_{args.plane}.png"
                plotUtils.plot_cube_slice(cube_file, atoms=atoms, plane=args.plane, cmap='RdBu_r', fname=output_file, colorbar_label='Orbital value')
                print(f"  Saved: {output_file}")
            print()
        
        # Plot density at specific points if requested
        if args.points:
            print("Evaluating density at specified points...")
            density_cubes = [c for c in cubes if 'abs2' in str(c) and 'diff' not in str(c)]
            if density_cubes:
                output_dir = Path(args.output_dir); output_dir.mkdir(exist_ok=True, parents=True)
                output_file = output_dir / f"density_{args.plane}.png"
                plotUtils.plot_cube_slice(density_cubes[0], atoms=atoms, plane=args.plane, cmap='viridis', fname=output_file, colorbar_label='Electron density')
                print(f"  Saved: {output_file}")
            else:
                print("  No density cube file found")
            print()
    
    # Return to original directory
    os.chdir('..')
    
    print("=== Example Complete ===")
    print(f"Results saved in: {workdir.absolute()}")
    print()
    print("Cube files can be visualized with:")
    print("  - VMD: vmd wp-*.cube")
    print("  - PyMOL: load wp-*.cube")
    print("  - ASE: from ase.io.cube import read_cube")

if __name__ == '__main__':
    main()
