"""Generate Bspline_PLQd.npy for NaCl using GPU Morse + DFT Coulomb.

Uses existing GridFF_cl GPU infrastructure:
- Pauli/London: computed via make_MorseFF kernel (GPU)
- Coulomb: loaded from DFT electrostatic_potential.cube
- Hbond: 0
"""

import os
import sys
import json
import numpy as np
import argparse

import matplotlib
matplotlib.use('Agg')


def _repo_root():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.realpath(os.path.join(here, '..', '..'))


sys.path.insert(0, _repo_root())

bohr2ang = 0.5291772109217
hartree2ev = 27.211396132


def _load_cube(cube_path, is_potential):
    """Load cube file and convert units.

    - potential: Hartree -> eV
    - density:   e/Bohr^3 -> e/Angstrom^3

    Returns array in (nx, ny, nz) C-order (z fastest).
    """
    with open(cube_path, 'r') as f:
        f.readline(); f.readline()
        line3 = f.readline().split()
        n_atoms = int(line3[0])
        origin = np.array([float(line3[1]), float(line3[2]), float(line3[3])]) * bohr2ang

        line4 = f.readline().split()
        nx = int(line4[0])
        dx = float(line4[1]) * bohr2ang

        line5 = f.readline().split()
        ny = int(line5[0])
        dy = float(line5[2]) * bohr2ang

        line6 = f.readline().split()
        nz = int(line6[0])
        dz = float(line6[3]) * bohr2ang

        for _ in range(n_atoms):
            f.readline()

        n_vals = nx * ny * nz
        data = np.fromfile(f, sep=' ', count=n_vals)
        data = data.reshape((nx, ny, nz))  # C-order: z fastest
        if is_potential:
            # DFT electrostatic potential is already in Volts (or eV), NOT Hartree
            # No conversion needed
            pass
        else:
            # Density: convert e/Bohr^3 to e/Angstrom^3
            data = data / (bohr2ang ** 3)
        return data, origin, (nx, ny, nz), (dx, dy, dz)


def compute_kinetic_energy_density_log(rho, dg, sigma_mult=5.0, rho_clamp=5.0):
    """Compute kinetic energy density via FFT Laplacian-of-Gaussian filtering.

    T(r) ≈ -c * ∇²ρ (smoothed) where c is a constant (ℏ²/2m in atomic units).
    Uses FFT convolution with LoG kernel for smooth derivatives.
    Strong Gaussian smoothing (sigma_mult=5.0) is essential for numerical stability
    due to sharp atomic density features.

    Args:
        rho: (nx, ny, nz) electron density array
        dg: (dx, dy, dz) grid spacing in Å
        sigma_mult: Gaussian sigma as multiple of grid spacing (default 5.0)
        rho_clamp: clamp density at this value to avoid nuclear cusp numerical issues
    Returns:
        tau: kinetic energy density array (au), scaled to be O(1)
    """
    # Clamp density to avoid nuclear cusp numerical instability
    rho_clamped = np.clip(rho, 0.0, rho_clamp)

    nx, ny, nz = rho_clamped.shape
    dx, dy, dz = dg
    # Gaussian sigma in physical units - use larger for stability
    sig_x = sigma_mult * dx
    sig_y = sigma_mult * dy
    sig_z = sigma_mult * dz

    # Build frequency grid (centered)
    kx = 2 * np.pi * np.fft.fftfreq(nx, dx)
    ky = 2 * np.pi * np.fft.fftfreq(ny, dy)
    kz = 2 * np.pi * np.fft.fftfreq(nz, dz)
    KX, KY, KZ = np.meshgrid(kx, ky, kz, indexing='ij')
    k2 = KX**2 + KY**2 + KZ**2

    # Gaussian filter in k-space: exp(-0.5 * sigma^2 * k^2)
    # This suppresses high-frequency noise before taking Laplacian
    gauss_k = np.exp(-0.5 * (sig_x**2 * KX**2 + sig_y**2 * KY**2 + sig_z**2 * KZ**2))

    # Laplacian in k-space: multiply by -k^2
    # LoG = Laplacian(Gaussian * f) -> -k^2 * gauss_k * FFT(f)
    rho_fft = np.fft.fftn(rho_clamped)
    log_fft = -k2 * gauss_k * rho_fft
    tau = np.fft.ifftn(log_fft).real

    # Scale: tau has units of density/length^2 from ∇²ρ
    # Scale by (grid spacing)^2 to make dimensionless-ish, then apply physical factor
    scale = (dx * dy * dz) ** (2.0/3.0)  # characteristic length squared
    tau = -tau * scale  # negative because ∇²ρ < 0 at density peaks

    # Clip extreme outliers for stability
    tau = np.clip(tau, -100.0, 100.0)
    return tau


def _save_cube(cube_path, data, origin, dg, comment='Generated cube'):
    """Save data array as Gaussian cube file.

    Cube format: z runs fastest, then y, then x.
    Input data is C-order (nx, ny, nz) where z is already fastest.
    We write in C-order to preserve z-fastest layout.

    Args:
        cube_path: output file path
        data: (nx, ny, nz) array (C-order: z fastest)
        origin: (3,) array in Å
        dg: (dx, dy, dz) grid spacing in Å
        comment: header comment
    """
    nx, ny, nz = data.shape
    dx, dy, dz = dg
    with open(cube_path, 'w') as f:
        f.write(f'{comment}\n')
        f.write('Cube generated by gen_gridff_nacl_gpu.py\n')
        # Origin (no atom count, just grid spec)
        f.write(f'    0 {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n')
        f.write(f'{nx:5d} {dx:12.6f}   0.000000   0.000000\n')
        f.write(f'{ny:5d}   0.000000 {dy:12.6f}   0.000000\n')
        f.write(f'{nz:5d}   0.000000   0.000000 {dz:12.6f}\n')
        # Flatten in C-order (z fastest) to match cube format
        flat = data.ravel(order='C')
        for i in range(0, len(flat), 6):
            vals = flat[i:i+6]
            line = ' '.join(f'{v:13.5e}' for v in vals)
            f.write(line + '\n')


def main():
    parser = argparse.ArgumentParser(description='Generate GridFF from DFT cubes and fit Pauli coefficients')
    parser.add_argument('--orient', type=str, default='Na', choices=['Na', 'Cl', 'hollow'],help='Which orientation to plot in 1D scan diagnostic (default: Na)')
    parser.add_argument('--log_sigma', type=float, default=6.0, help='LoG Gaussian sigma as multiple of grid spacing (default: 2.0, units: voxels)')
    parser.add_argument('--plot_rho_tau', action='store_true', help='Plot rho (ch0) and tau (ch3) profiles over Na/Cl atoms')
    parser.add_argument('--hbond_model', type=str, default='cl_morse', choices=['tau', 'cl_morse'], help='Hbond correction model: tau (kinetic energy density) or cl_morse (Cl repulsive Morse) (default: cl_morse)')
    parser.add_argument('--cl_R_eq',  type=float, default=1.80,   help='Cl Morse R_eq in Angstrom (default: 1.80)')
    parser.add_argument('--cl_D_e',   type=float, default=0.0116,  help='Cl Morse D_e in eV (default: 0.0116)')
    parser.add_argument('--cl_alpha', type=float, default=1.5,    help='Cl Morse exponent alpha in 1/Angstrom (default: 1.5)')
    parser.add_argument('--plot_log', action='store_true', help='Plot hbond channel on logarithmic scale')
    parser.add_argument('--vmax_xz', type=float, default=0.25, help='XZ plot symmetric color range in eV (default: 0.35, uses +/- this value)')
    parser.add_argument('--plot_mol_samples', action=argparse.BooleanOptionalAction, default=True, help='Plot H2O sample atoms in 2D imshow plots (default: True)')
    parser.add_argument('--xy_same_scale_as_xz', action='store_true', help='Use same color scale for XY plot as XZ plot (default: False)')
    parser.add_argument('--xy_z_height', type=float, default=2.5, help='Z-height for XY slice plot in Angstrom (default: 2.5)')
    parser.add_argument('--z_profile_range', type=float, nargs=2, default=[0.0, 6.0], help='Z-profile plot range in Angstrom (default: 0.0 6.0)')
    args = parser.parse_args()

    ROOT = _repo_root()
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'out_fdbm_dft_gridff')
    os.makedirs(out_dir, exist_ok=True)
    
    dft_data_dir = os.path.join(ROOT, 'tests', 'tSurf', 'small_mols_NaCl_New')
    density_cube   = os.path.join(dft_data_dir, '4-elec_pot_chr_den', 'charge_density.cube')
    potential_cube = os.path.join(dft_data_dir, '4-elec_pot_chr_den', 'electrostatic_potential.cube')
    sub_path = os.path.join(dft_data_dir, '0-geoms', 'NaCl.xyz')
    
    print('=== Generating GridFF for NaCl (DFT cube density+potential) ===')
    
    # Load DFT density & potential (authoritative)
    rho, g0_rho, (nx, ny, nz), dg_rho = _load_cube(density_cube, is_potential=False)
    phi, g0_phi, n_phi, dg_phi = _load_cube(potential_cube, is_potential=True)
    if tuple(n_phi) != (nx, ny, nz):
        raise RuntimeError(f'Cube shape mismatch: density {nx,ny,nz} vs potential {tuple(n_phi)}')
    if not (np.allclose(g0_rho, g0_phi) and np.allclose(dg_rho, dg_phi)):
        raise RuntimeError(f'Cube grid mismatch: g0_rho={g0_rho} g0_phi={g0_phi} dg_rho={dg_rho} dg_phi={dg_phi}')
    g0 = g0_rho
    dg = dg_rho
    # Correct electrostatic potential: subtract V0 (average of top slice at z = end of cell)
    # This removes the arbitrary constant from FFT Poisson solver
    V0 = phi[:, :, -1].mean()
    phi = phi - V0
    print(f'Corrected electrostatics by subtracting V0={V0:.6f} eV (top slice average)')
    # Invert sign: DFT Hartree potential is for electrons (opposite sign to physical electrostatic)
    phi = -phi
    print(f'Inverted sign of electrostatic potential (Hartree for electrons -> physical)')
    
    print(f'DFT grid: ({nx}, {ny}, {nz}), g0={g0}, dg={dg}')
    print(f'DFT density range:   [{rho.min():.6e}, {rho.max():.6e}] e/A^3')
    print(f'DFT potential range: [{phi.min():.6f}, {phi.max():.6f}] eV (after V0 correction)')
    
    # Load substrate atoms
    from pyBall.OCL.Surface_utils import load_substrate_xyz_with_lvec
    sub_data = load_substrate_xyz_with_lvec(sub_path)
    sub_apos = sub_data['apos']
    sub_enames = sub_data['enames']
    # lvec from substrate might be None, use DFT grid lattice instead
    lvec = sub_data['lvec']
    if lvec is None:
        # Build lattice from DFT grid parameters
        lvec = np.zeros((4, 3), dtype=np.float64)
        lvec[0] = g0
        lvec[1] = [nx * dg[0], 0.0, 0.0]
        lvec[2] = [0.0, ny * dg[1], 0.0]
        lvec[3] = [0.0, 0.0, nz * dg[2]]

    print(f'Substrate: {len(sub_apos)} atoms')

    # Channels from DFT cubes (authoritative)
    pauli   = np.ascontiguousarray(rho.astype(np.float32))
    london  = np.zeros((nx, ny, nz), dtype=np.float32)
    coulomb = np.ascontiguousarray(phi.astype(np.float32))

    # 4th channel: either tau (kinetic energy density) or Cl repulsive Morse
    if args.hbond_model == 'tau':
        print('\nComputing kinetic energy density (LoG-filtered Laplacian of rho)...')
        tau_raw = compute_kinetic_energy_density_log(rho, dg, sigma_mult=args.log_sigma)
        tau = np.ascontiguousarray(tau_raw.astype(np.float32))
        tau_range = (float(tau.min()), float(tau.max()))
        print(f'Kinetic energy density range: [{tau_range[0]:.4e}, {tau_range[1]:.4e}] (au)')
        # Save kinetic energy density cube for review
        tau_cube_path = os.path.join(dft_data_dir, 'kinetic_energy_density.cube')
        _save_cube(tau_cube_path, tau_raw, g0, dg, 'Kinetic Energy Density (LoG of rho)')
        print(f'Saved kinetic energy density cube: {tau_cube_path}')
    elif args.hbond_model == 'cl_morse':
        print('\nComputing Cl repulsive field on grid (GPU, GridFF_cl.make_MorseFF)...')
        from pyBall.OCL.Surface_utils import compute_cl_repulsive_on_grid
        cl_mask = np.array([e == 'Cl' for e in sub_enames])
        cl_apos = sub_apos[cl_mask]  # only Cl atoms in substrate
        print(f'  Using {len(cl_apos)} Cl atoms')
        # Lattice from DFT grid (g0 not shifted yet)
        Lx = nx * dg[0]; Ly = ny * dg[1]; Lz = nz * dg[2]
        lvec = np.array([[Lx, 0.0, 0.0], [0.0, Ly, 0.0], [0.0, 0.0, Lz]], dtype=np.float64)
        cl_rep = compute_cl_repulsive_on_grid(
            cl_apos, g0, dg, (nx, ny, nz), lvec, nPBC=(4, 4, 0),
            R_eq=args.cl_R_eq, D_e=args.cl_D_e, alphaMorse=args.cl_alpha, R_damp=0.1
        )
        tau = np.ascontiguousarray(cl_rep.astype(np.float32))  # named tau to keep downstream code
        tau_range = (float(tau.min()), float(tau.max()))
        print(f'Cl repulsive field range: [{tau_range[0]:.4e}, {tau_range[1]:.4e}] eV')
        # Save Cl repulsive cube for review
        tau_cube_path = os.path.join(dft_data_dir, 'cl_repulsive.cube')
        _save_cube(tau_cube_path, cl_rep, g0, dg, 'Cl Morse Repulsive Field')
        print(f'Saved Cl repulsive cube: {tau_cube_path}')

    # Shift g0[2] so that z=0 is at the top substrate atom
    z_top_sub = sub_apos[:, 2].max()
    g0 = np.array([g0[0], g0[1], g0[2] - z_top_sub], dtype=np.float32)
    print(f'Shifted g0 so z=0 at top substrate atom (z_top={z_top_sub:.3f} A)')

    # Assemble GridFF: (nx, ny, nz, 4) as float32 contiguous
    # Channel order: [Pauli(rho), London(0), Coulomb(phi), Hbond(tau or Cl repulsive)]
    gridff = np.ascontiguousarray(np.stack([pauli, london, coulomb, tau], axis=3).astype(np.float32))

    # Save
    gridff_path = os.path.join(dft_data_dir, 'Bspline_PLQd.npy')
    np.save(gridff_path, gridff)
    print(f'\nSaved GridFF to: {gridff_path}')

    # Save metadata
    meta = {
        'ns': [nx, ny, nz],
        'g0': g0.tolist(),
        'dg': list(dg),
        'grid_type': 'Bspline_PLQd',
        'generation_script': 'gen_gridff_nacl_gpu.py',
        'channels': ['Pauli (charge_density.cube)', 'London (0)', 'Coulomb (electrostatic_potential.cube)', f'Hbond ({args.hbond_model})'],
        'hbond_model': args.hbond_model,
        'hbond_range': tau_range,
        'note': f'Pauli channel loaded from DFT charge_density.cube. Coulomb from electrostatic_potential.cube. Hbond (4th channel) = {args.hbond_model}.'
    }
    meta_path = os.path.join(dft_data_dir, 'Bspline_PLQd_meta.json')
    with open(meta_path, 'w') as f:
        json.dump(meta, f, indent=2)
    print(f'Saved metadata to: {meta_path}')

    # Plot rho and hbond profiles over Na/Cl atoms if requested
    if args.plot_rho_tau:
        import matplotlib.pyplot as plt
        hbond_label = 'tau (kinetic)' if args.hbond_model == 'tau' else 'Cl repulsive'
        hbond_ylabel = 'tau [au]' if args.hbond_model == 'tau' else 'Cl repulsive [eV]'
        print(f'\n=== Plotting rho (clamped) and {hbond_label} vs z over Na/Cl ===')
        # Find top Na and Cl atoms
        z_top = sub_apos[:, 2].max()
        na_pos = None; cl_pos = None
        for i, (pos, ename) in enumerate(zip(sub_apos, sub_enames)):
            if ename == 'Na' and abs(pos[2] - z_top) < 0.1:
                na_pos = pos
            elif ename == 'Cl' and abs(pos[2] - z_top) < 0.1:
                cl_pos = pos
        if na_pos is None or cl_pos is None:
            raise RuntimeError('Could not find top Na or Cl atom')
        print(f'Na position: {na_pos}')
        print(f'Cl position: {cl_pos}')
        # Extract vertical profiles
        def extract_profile(pos_xy):
            ix = int((pos_xy[0] - g0[0]) / dg[0]) % nx
            iy = int((pos_xy[1] - g0[1]) / dg[1]) % ny
            rho = gridff[ix, iy, :, 0]
            hbond = gridff[ix, iy, :, 3]
            z = g0[2] + np.arange(nz) * dg[2]
            return z, rho, hbond
        z_na, rho_na, hbond_na = extract_profile(na_pos)
        z_cl, rho_cl, hbond_cl = extract_profile(cl_pos)
        # Clamp density for plotting
        rho_clamp = 5.0
        rho_na_clamped = np.clip(rho_na, 0.0, rho_clamp)
        rho_cl_clamped = np.clip(rho_cl, 0.0, rho_clamp)
        # Filter to z-range [0, 4] for y-limit calculation to avoid far-field 1e-35 values
        mask_na = (z_na >= 0.0) & (z_na <= 4.0)
        mask_cl = (z_cl >= 0.0) & (z_cl <= 4.0)
        # Plot both vs z
        fig, axs = plt.subplots(1, 2, figsize=(12, 5), sharex=True)
        # Na
        ax = axs[0]
        if args.plot_log:
            ax.plot(z_na, rho_na_clamped, 'b-', lw=1.5, label='rho (clamped)')
            ax.plot(z_na, hbond_na, 'r-', lw=1.5, label=hbond_label)
            ax.set_ylabel('log scale', color='k')
            ax.tick_params(axis='y', labelcolor='k')
            ax.set_yscale('log')
            # Set y-limits based on data within z-range [0,4]
            y_max = max(rho_na_clamped[mask_na].max(), hbond_na[mask_na].max())
            y_min = min(rho_na_clamped[mask_na][rho_na_clamped[mask_na] > 0].min(), hbond_na[mask_na][hbond_na[mask_na] > 0].min())
            ax.set_ylim(y_min * 0.5, y_max * 2.0)
        else:
            axr = ax.twinx()
            ax.plot(z_na, rho_na_clamped, 'b-', lw=1.5, label='rho (clamped)')
            axr.plot(z_na, hbond_na, 'r-', lw=1.5, label=hbond_label)
            ax.set_xlabel('z [A]'); ax.set_ylabel('rho (clamped) [e/A^3]', color='b')
            axr.set_ylabel(hbond_ylabel, color='r')
            ax.tick_params(axis='y', labelcolor='b'); axr.tick_params(axis='y', labelcolor='r')
        ax.set_xlabel('z [A]')
        ax.set_title(f'Na atom (ix={int((na_pos[0]-g0[0])/dg[0])%nx}, iy={int((na_pos[1]-g0[1])/dg[1])%ny})')
        ax.grid(True, alpha=0.3); ax.legend(loc='upper left')
        ax.set_xlim(0.0, 4.0)
        # Cl
        ax = axs[1]
        if args.plot_log:
            ax.plot(z_cl, rho_cl_clamped, 'b-', lw=1.5, label='rho (clamped)')
            ax.plot(z_cl, hbond_cl, 'r-', lw=1.5, label=hbond_label)
            ax.set_ylabel('log scale', color='k')
            ax.tick_params(axis='y', labelcolor='k')
            ax.set_yscale('log')
            # Set y-limits based on data within z-range [0,4]
            y_max = max(rho_cl_clamped[mask_cl].max(), hbond_cl[mask_cl].max())
            y_min = min(rho_cl_clamped[mask_cl][rho_cl_clamped[mask_cl] > 0].min(), hbond_cl[mask_cl][hbond_cl[mask_cl] > 0].min())
            ax.set_ylim(y_min * 0.5, y_max * 2.0)
        else:
            axr = ax.twinx()
            ax.plot(z_cl, rho_cl_clamped, 'b-', lw=1.5, label='rho (clamped)')
            axr.plot(z_cl, hbond_cl, 'r-', lw=1.5, label=hbond_label)
            ax.set_xlabel('z [A]'); ax.set_ylabel('rho (clamped) [e/A^3]', color='b')
            axr.set_ylabel(hbond_ylabel, color='r')
            ax.tick_params(axis='y', labelcolor='b'); axr.tick_params(axis='y', labelcolor='r')
        ax.set_xlabel('z [A]')
        ax.set_title(f'Cl atom (ix={int((cl_pos[0]-g0[0])/dg[0])%nx}, iy={int((cl_pos[1]-g0[1])/dg[1])%ny})')
        ax.grid(True, alpha=0.3); ax.legend(loc='upper left')
        ax.set_xlim(0.0, 4.0)
        if args.hbond_model == 'tau':
            suptitle = f'rho (clamped={rho_clamp}) and tau vs z, LoG sigma={args.log_sigma}'
        else:
            suptitle = f'rho (clamped={rho_clamp}) and Cl repulsive vs z, R_eq={args.cl_R_eq} D_e={args.cl_D_e} alpha={args.cl_alpha}'
        fig.suptitle(suptitle, fontsize=12)
        plt.tight_layout()
        rho_hbond_path = os.path.join(out_dir, f'rho_{args.hbond_model}_profiles.png')
        plt.savefig(rho_hbond_path, dpi=150)
        print(f'Saved rho/{args.hbond_model} profile plot: {rho_hbond_path}')
        plt.close(fig)

    # Generate diagnostic plots
    from pyBall.OCL import Surface_utils as su
    
    def _load_xyz_with_charges(xyz_path):
        with open(xyz_path, 'r') as f:
            lines = f.readlines()
        n = int(lines[0].strip())
        names = []
        pos = []
        qs = []
        for i in range(2, 2 + n):
            w = lines[i].split()
            names.append(w[0])
            pos.append((float(w[1]), float(w[2]), float(w[3])))
            qs.append(float(w[4]) if len(w) > 4 else 0.0)
        return np.array(pos, dtype=np.float32), np.array(names), np.array(qs, dtype=np.float32)
    
    mol_path = os.path.join(ROOT, 'cpp', 'common_resources', 'xyz', 'H2O.xyz')
    apos, names, charges = _load_xyz_with_charges(mol_path)
    apos0 = (apos - apos.mean(axis=0)).astype(np.float32)
    
    z_vals = np.linspace(1.4, 10.0, 33)
    def _make_transforms_zscan(xy=(0.0, 0.0), z_vals=None, phis=None):
        if z_vals is None:
            z_vals = np.linspace(1.4, 10.0, 33)
        if phis is None:
            phis = np.array([0.0], dtype=np.float32)
        z_vals = np.asarray(z_vals, dtype=np.float32)
        phis = np.asarray(phis, dtype=np.float32)
        Ts = []
        for phi in phis:
            c = float(np.cos(phi)); s = float(np.sin(phi))
            R = np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]], dtype=np.float32)
            for z in z_vals:
                T = np.zeros((3, 4), dtype=np.float32)
                T[:, :3] = R
                T[:, 3] = np.array([xy[0], xy[1], float(z)], dtype=np.float32)
                Ts.append(T)
        return np.array(Ts, dtype=np.float32)
    
    T_z = _make_transforms_zscan(xy=(0.0, 0.0), z_vals=z_vals, phis=[0.0])
    apos_all = np.zeros((len(T_z), len(apos0), 3), dtype=np.float32)
    for i, T in enumerate(T_z):
        R = T[:, :3]
        t = T[:, 3]
        apos_all[i] = (apos0 @ R.T) + t
    
    n_samples_plot = min(100, len(apos_all))
    mol_apos_subset = apos_all[:n_samples_plot]

    from pyBall.OCL.MMparams import read_element_types
    element_types = read_element_types(os.path.join(ROOT, 'cpp', 'common_resources', 'ElementTypes.dat'))
    alpha_morse = 1.8
    
    def _req_to_plq(req, alpha=1.8):
        R, E, Q, H = req
        e = np.exp(alpha * R)
        cL = e * E
        cP = e * cL
        return (cP, cL, Q, 0.0)
    
    req_H = (element_types['H'].RvdW, np.sqrt(element_types['H'].EvdW), 
             charges[np.where(np.array(names) == 'H')[0][0]], 0.0)
    req_O = (element_types['O'].RvdW, np.sqrt(element_types['O'].EvdW), 
             charges[np.where(np.array(names) == 'O')[0][0]], 0.0)
    
    plq_H = _req_to_plq(req_H, alpha=alpha_morse)
    plq_O = _req_to_plq(req_O, alpha=alpha_morse)
    
    # iz_top at specified z-height above surface: iz = (xy_z_height - g0[2]) / dg[2]
    iz_top = int((args.xy_z_height - g0[2]) / dg[2])
    print(f'Using iz_top={iz_top} (z={g0[2] + iz_top*dg[2]:.3f} A)')

    # Single combined plot with H as primary (XY/XZ) and both H+O in Z-profiles
    diag_path_h = os.path.join(out_dir, 'total_potential_H_atom.png')
    su.plot_alignment_summary(gridff, g0, dg, sub_apos, sub_enames,
                              save_path=diag_path_h, iz_top=iz_top, iy_center=64,
                              z_atom_range=5.0, mol_apos=mol_apos_subset, mol_enames=names,
                              plq_coeffs=(plq_H[0], plq_H[1], plq_H[2]),
                              plq_coeffs2=(plq_O[0], plq_O[1], plq_O[2]),
                              zmin_offset=2.0, z_ylim=(-2.0, 2.0), vmin_vmax_xz=(-args.vmax_xz, args.vmax_xz),
                              plot_mol_samples=args.plot_mol_samples, xy_same_scale_as_xz=args.xy_same_scale_as_xz,
                              z_profile_range=tuple(args.z_profile_range), elem_name='H', elem_name2='O', H_H=0.0, H_O=0.0)
    print('Saved H atom plot:', diag_path_h)

    # O as primary (XY/XZ) and both H+O in Z-profiles
    diag_path_o = os.path.join(out_dir, 'total_potential_O_atom.png')
    su.plot_alignment_summary(gridff, g0, dg, sub_apos, sub_enames,
                              save_path=diag_path_o, iz_top=iz_top, iy_center=64,
                              z_atom_range=5.0, mol_apos=mol_apos_subset, mol_enames=names,
                              plq_coeffs=(plq_O[0], plq_O[1], plq_O[2]),
                              plq_coeffs2=(plq_H[0], plq_H[1], plq_H[2]),
                              zmin_offset=2.0, z_ylim=(-2.0, 2.0), vmin_vmax_xz=(-args.vmax_xz, args.vmax_xz),
                              plot_mol_samples=args.plot_mol_samples, xy_same_scale_as_xz=args.xy_same_scale_as_xz,
                              z_profile_range=tuple(args.z_profile_range), elem_name='O', elem_name2='H')
    print('Saved O atom plot:', diag_path_o)

    # === Fit P, L and charges from DFT data ===
    print('\n=== Fitting P, L coefficients from DFT data ===')

    # Load consolidated DFT data (use both H2O-H and H2O-O if available)
    dft_paths = [
        os.path.join(ROOT, 'tests', 'tMMFF', 'H2O-H_matched.npz'),
        os.path.join(ROOT, 'tests', 'tMMFF', 'H2O-O_matched.npz'),
    ]
    dsets = []
    for p in dft_paths:
        if os.path.exists(p):
            dsets.append((os.path.basename(p).replace('_matched.npz', ''), np.load(p)))
        else:
            print(f'Warning: DFT data not found at {p}')
    if len(dsets) == 0:
        print('No DFT matched datasets found. Run: python consolidate_dft_data.py match --molecule H2O-H (and H2O-O)')
    else:
        # concatenate datasets
        coords = np.concatenate([ds['coords'] for _, ds in dsets], axis=0).copy()
        energies = np.concatenate([ds['energies'] for _, ds in dsets], axis=0)
        enames = dsets[0][1]['enames']
        ix = np.concatenate([ds['ix'] for _, ds in dsets], axis=0)
        iy = np.concatenate([ds['iy'] for _, ds in dsets], axis=0)
        orientxy = np.concatenate([ds['orientxy'] for _, ds in dsets], axis=0)
        orientz = np.concatenate([ds['orientz'] for _, ds in dsets], axis=0)
        zdist = np.concatenate([ds['zdist'] for _, ds in dsets], axis=0)
        mol_tag = np.concatenate([np.full(len(ds['energies']), name, dtype=object) for name, ds in dsets], axis=0)

        # CRITICAL: grid origin g0 was shifted so that z=0 is at top substrate atom.
        # DFT xyz coordinates are still in the original frame (same as substrate xyz).
        # Therefore shift molecule coordinates by the same z_top_sub before sampling.
        coords[:, :, 2] -= z_top_sub

        print(f'Loaded {len(coords)} configurations from DFT data')
        print(f'Element names: {list(enames)}')
        print(f'Energy range: [{energies.min():.6f}, {energies.max():.6f}] eV')

        # Compute interaction energy by subtracting baseline at farthest z within each group.
        # Group key: (mol, ix, iy, orientxy, orientz)
        E0 = np.zeros_like(energies, dtype=np.float64)
        uniq_keys = {}
        for i in range(len(energies)):
            k = (str(mol_tag[i]), int(ix[i]), int(iy[i]), str(orientxy[i]), int(orientz[i]))
            uniq_keys.setdefault(k, []).append(i)
        for k, idxs in uniq_keys.items():
            zz = zdist[idxs]
            zmax = float(np.max(zz))
            mask = np.isclose(zz, zmax, rtol=0.0, atol=1e-6)
            imax = np.array(idxs, dtype=int)[mask]
            if len(imax) == 0: raise RuntimeError(f'No max-z samples for group {k} zmax={zmax}')
            E0_val = float(np.mean(energies[imax]))
            E0[idxs] = E0_val
        E_int = energies - E0
        print(f'Interaction energy range (E-E0): [{E_int.min():.6f}, {E_int.max():.6f}] eV')

        # Restrict fit: only tilt=0, specific scan configs, E_int <= Eint_max
        # Also apply exponential weighting to prioritize near-minimum energies
        Eint_max = 0.5
        scan_tilt_fit = 0
        # scan configs: (mol, ix, iy) that we want to fit
        # Focus only on the two key bonding profiles:
        # - H2O-H over Cl (H-down hydrogen bond)
        # - H2O-O over Na (electrostatic minimum)
        fit_scan_configs = [
            ('H2O-H', 0, 0),  # Cl site
            ('H2O-O', 6, 0),  # Na site
        ]
        mask_scan = np.zeros(len(E_int), dtype=bool)
        for mol_f, ix_f, iy_f in fit_scan_configs:
            mask_scan |= (mol_tag == mol_f) & (ix == ix_f) & (iy == iy_f) & (orientz == scan_tilt_fit)
        mask_fit = mask_scan & (E_int <= Eint_max)
        n_keep = int(np.count_nonzero(mask_fit))
        if n_keep == 0: raise RuntimeError(f'No samples satisfy fit criteria')
        print(f'Fit filter: tilt={scan_tilt_fit}, scan configs only, E_int <= {Eint_max:.3f} eV  ->  {n_keep} / {len(E_int)} configs')
        # Exponential weighting: w = exp(-E_int / kT), prioritize near-minimum
        kT_weight = 0.2  # eV
        weights = np.exp(-E_int / kT_weight)
        weights[~mask_fit] = 0.0
        weights[mask_fit] /= weights[mask_fit].max()  # normalize so max weight = 1
        print(f'Weighting: exp(-E_int/{kT_weight:.2f}), effective weight range [{weights[mask_fit].min():.4f}, {weights[mask_fit].max():.4f}]')
        # crude per-dataset stats
        for name, _ in dsets:
            m = (mol_tag == name) & mask_fit
            nk = int(np.count_nonzero(m))
            nt = int(np.count_nonzero(mol_tag == name))
            print(f'  {name}: {nk} / {nt} kept')

        # Sample GridFF channels at atom positions for all configurations
        n_configs = len(coords)
        n_atoms = coords.shape[1]
        n_types = 2

        idx_pauli = 0
        idx_coulomb = 2

        print(f'Sampling GridFF channels at {n_configs * n_atoms} atom positions...')

        n_clamp = 0
        n_wrapx = 0
        n_wrapy = 0
        ix_min =  10**9; iy_min =  10**9; iz_min =  10**9
        ix_max = -10**9; iy_max = -10**9; iz_max = -10**9

        def sample_gridff(pos, gridff, g0, dg):
            """Sample GridFF numpy array at position (x, y, z) using trilinear interpolation.

            - x/y: periodic wrap
            - z: clamp

            Returns:
                vals: (nch,) float32
                clamped_z: bool
                (ix0,iy0,iz0): int base grid indices before wrap/clamp (floor)
                (ix,iy,iz): int wrapped/clamped base indices used on grid
            """
            nx, ny, nz, nch = gridff.shape
            fx = (pos[0] - g0[0]) / dg[0]
            fy = (pos[1] - g0[1]) / dg[1]
            fz = (pos[2] - g0[2]) / dg[2]
            ix0 = int(np.floor(fx)); iy0 = int(np.floor(fy)); iz0 = int(np.floor(fz))
            tx = fx - ix0; ty = fy - iy0; tz = fz - iz0

            ix = ix0 % nx
            iy = iy0 % ny
            clamped_z = (iz0 < 0) or (iz0 >= nz - 1)
            iz = max(0, min(iz0, nz - 2))
            iz1 = iz + 1

            ix1 = (ix + 1) % nx
            iy1 = (iy + 1) % ny

            # gather 8 corners
            c000 = gridff[ix , iy , iz , :]
            c100 = gridff[ix1, iy , iz , :]
            c010 = gridff[ix , iy1, iz , :]
            c110 = gridff[ix1, iy1, iz , :]
            c001 = gridff[ix , iy , iz1, :]
            c101 = gridff[ix1, iy , iz1, :]
            c011 = gridff[ix , iy1, iz1, :]
            c111 = gridff[ix1, iy1, iz1, :]

            # trilinear interpolation
            c00 = c000*(1.0-tx) + c100*tx
            c10 = c010*(1.0-tx) + c110*tx
            c01 = c001*(1.0-tx) + c101*tx
            c11 = c011*(1.0-tx) + c111*tx
            c0  = c00 *(1.0-ty) + c10 *ty
            c1  = c01 *(1.0-ty) + c11 *ty
            vals = c0  *(1.0-tz) + c1  *tz
            return vals, clamped_z, (ix0, iy0, iz0), (ix, iy, iz)

        # Fixed nonlinear parameters
        beta_fit = 1.15
        dz_shift_fit = 0.0
        idx_tau = 3

        b = E_int
        idx_fit = np.where(mask_fit)[0]
        if len(idx_fit) == 0: raise RuntimeError('mask_fit is empty')
        w_fit = weights[idx_fit]
        b_fit0 = b[idx_fit]
        sqw = np.sqrt(w_fit)

        # Sample all needed channels for fit configurations (dz=0 fixed)
        nfit = len(idx_fit)
        rhoH = np.zeros(nfit, dtype=np.float64)
        rhoO = np.zeros(nfit, dtype=np.float64)
        phiH = np.zeros(nfit, dtype=np.float64)
        phiO = np.zeros(nfit, dtype=np.float64)
        tauH = np.zeros(nfit, dtype=np.float64)
        tauO = np.zeros(nfit, dtype=np.float64)
        for ii, i in enumerate(idx_fit):
            for j, ename in enumerate(enames):
                pos = coords[i, j].copy()
                vals, clamped_z, (ix0, iy0, iz0), (ixg, iyg, izg) = sample_gridff(pos, gridff, g0, dg)
                if clamped_z: n_clamp += 1
                if ix0 != ixg: n_wrapx += 1
                if iy0 != iyg: n_wrapy += 1
                if ixg < ix_min: ix_min = ixg
                if iyg < iy_min: iy_min = iyg
                if izg < iz_min: iz_min = izg
                if ixg > ix_max: ix_max = ixg
                if iyg > iy_max: iy_max = iyg
                if izg > iz_max: iz_max = izg
                if ename == 'H':
                    rhoH[ii] += abs(float(vals[idx_pauli]))**beta_fit
                    phiH[ii] += float(vals[idx_coulomb])
                    tauH[ii] += float(vals[idx_tau])
                elif ename == 'O':
                    rhoO[ii] += abs(float(vals[idx_pauli]))**beta_fit
                    phiO[ii] += float(vals[idx_coulomb])
                    tauO[ii] += float(vals[idx_tau])

        # Weighted least squares: fit P_H, P_O, H_H, H_O, q_H (5 linear params)
        # Model: E = P_H*rhoH^beta + P_O*rhoO^beta + H_H*tauH + H_O*tauO + q_H*(phiH - 2*phiO)
        # Design matrix columns: [rhoH, rhoO, tauH, tauO, (phiH-2*phiO)]
        # NOTE: This fit is typically ill-conditioned; stabilize with column scaling + ridge w/ priors.
        phi_net = phiH - 2.0 * phiO
        A = np.column_stack([rhoH, rhoO, tauH, tauO, phi_net]).astype(np.float64)
        A_w = A * sqw[:, None]
        b_w = (b_fit0 * sqw).astype(np.float64)
        cond = np.linalg.cond(A_w)
        print(f'Design matrix condition number (unscaled): {cond:.2e}')

        # Column scaling to improve conditioning
        col_scale = np.sqrt(np.mean(A_w*A_w, axis=0))
        col_scale[col_scale == 0.0] = 1.0
        A_ws = A_w / col_scale[None, :]
        cond_s = np.linalg.cond(A_ws)
        print(f'Design matrix condition number (scaled):   {cond_s:.2e}')

        # Ridge with priors (physics regularization): penalize deviations from reasonable values
        # Prior defaults:
        # - P_H, P_O around diagnostic atom params (from vdW)
        # - H_H, H_O around 0 (let data pull them if needed)
        # - q_H around RESP reference
        prior = np.array([float(plq_H[0]), float(plq_O[0]), 0.0, 0.0, float(plq_H[2])], dtype=np.float64)

        # Characteristic scales (units): tune to keep parameters in physical ballpark unless data strongly disagrees
        # (these are not hard constraints, just a stabilizer)
        prior_scale = np.array([30.0, 300.0, 300.0, 300.0, 0.5], dtype=np.float64)
        ridge_strength = 1.0  # larger -> closer to prior
        lam = ridge_strength * (1.0 / (prior_scale*prior_scale))

        # Solve: min ||A_ws*c_s - b||^2 + ||sqrt(lam_s)*(c_s - prior_s)||^2
        # where c = c_s / col_scale, and lam_s operates in scaled coordinates
        prior_s = prior * col_scale
        lam_s = lam / (col_scale*col_scale)
        ATA = A_ws.T @ A_ws
        ATb = A_ws.T @ b_w
        M = ATA + np.diag(lam_s)
        rhs = ATb + lam_s * prior_s
        c_s = np.linalg.solve(M, rhs)
        c_fit = c_s / col_scale
        PH_fit, PO_fit, HH_fit, HO_fit, qH_fit = c_fit
        qO_fit = -2.0 * qH_fit
        residuals = float(np.sqrt(np.mean((A_w @ c_fit - b_w)**2)))

        print(f'\nLinear fit (beta={beta_fit}, dz=0): P_H, P_O, H_H, H_O, q_H free (ridge+priors)')
        print(f'\n=== Fitted coefficients ===')
        print(f'P_H = {PH_fit:.6f} (diagnostic from atom params: {plq_H[0]:.6f})')
        print(f'P_O = {PO_fit:.6f} (diagnostic from atom params: {plq_O[0]:.6f})')
        print(f'H_H = {HH_fit:.6f}')
        print(f'H_O = {HO_fit:.6f}')
        print(f'q_H = {qH_fit:.6f} (RESP ref: {plq_H[2]:.6f})')
        print(f'q_O = {qO_fit:.6f}')
        print(f'beta = {beta_fit} (fixed)')
        print(f'dz  = {dz_shift_fit} (fixed)')
        print(f'wRMS residual: {residuals:.6f}')

        # Save fitted coefficients
        fit_coeffs = {
            'P_H': float(PH_fit), 'P_O': float(PO_fit),
            'H_H': float(HH_fit), 'H_O': float(HO_fit),
            'q_H': float(qH_fit), 'q_O': float(qO_fit),
            'beta': float(beta_fit), 'dz': float(dz_shift_fit),
            'diagnostic_P_H': float(plq_H[0]), 'diagnostic_P_O': float(plq_O[0]),
            'resp_q_H': float(plq_H[2]), 'resp_q_O': float(plq_O[2]),
            'wRMS_residual': float(residuals),
            'fit_dz_shift': float(dz_shift_fit),
            'interaction_energy_range': [float(E_int.min()), float(E_int.max())],
            'fit_Eint_max': float(Eint_max),
            'fit_n_keep': int(n_keep),
            'z_clamp_fraction': float(n_clamp / (n_configs * n_atoms)),
            'xy_wrap_counts': [int(n_wrapx), int(n_wrapy)],
            'datasets': [name for name, _ in dsets]
        }
        fit_path = os.path.join(out_dir, 'fitted_PLQ_coeffs.json')
        with open(fit_path, 'w') as f:
            json.dump(fit_coeffs, f, indent=2)
        print(f'Saved fitted coefficients to: {fit_path}')

        # Generate comparison plots with fitted coefficients
        print('\nGenerating comparison plot with fitted coefficients...')
        diag_path_fit = os.path.join(out_dir, 'total_potential_H_atom_fitted.png')
        su.plot_alignment_summary(gridff, g0, dg, sub_apos, sub_enames,
                                  save_path=diag_path_fit, iz_top=iz_top, iy_center=64,
                                  z_atom_range=5.0, mol_apos=mol_apos_subset, mol_enames=names,
                                  plq_coeffs=(PH_fit, 0.0, qH_fit),
                                  plq_coeffs2=(PO_fit, 0.0, qO_fit),
                                  zmin_offset=2.0, z_ylim=(-2.0, 2.0), vmin_vmax_xz=(-args.vmax_xz, args.vmax_xz),
                              plot_mol_samples=args.plot_mol_samples, xy_same_scale_as_xz=args.xy_same_scale_as_xz,
                              z_profile_range=tuple(args.z_profile_range), elem_name='H', elem_name2='O', H_H=HH_fit, H_O=HO_fit)
        print('Saved fitted H atom plot:', diag_path_fit)

        diag_path_fit_o = os.path.join(out_dir, 'total_potential_O_atom_fitted.png')
        su.plot_alignment_summary(gridff, g0, dg, sub_apos, sub_enames,
                                  save_path=diag_path_fit_o, iz_top=iz_top, iy_center=64,
                                  z_atom_range=5.0, mol_apos=mol_apos_subset, mol_enames=names,
                                  plq_coeffs=(PO_fit, 0.0, qO_fit),
                                  plq_coeffs2=(PH_fit, 0.0, qH_fit),
                                  zmin_offset=2.0, z_ylim=(-2.0, 2.0), vmin_vmax_xz=(-args.vmax_xz, args.vmax_xz),
                              plot_mol_samples=args.plot_mol_samples, xy_same_scale_as_xz=args.xy_same_scale_as_xz,
                              z_profile_range=tuple(args.z_profile_range), elem_name='O', elem_name2='H', H_H=HH_fit, H_O=HO_fit)
        print('Saved fitted O atom plot:', diag_path_fit_o)

        # === 1D scan diagnostic: DFT vs fitted interaction energies ===
        print('\n=== 1D scan diagnostic: DFT vs fitted ===')
        import matplotlib.pyplot as plt
        panel_mols  = ['H2O-H', 'H2O-H', 'H2O-O', 'H2O-O']
        panel_sites = ['Na', 'Cl', 'Na', 'Cl']
        panel_ix    = [6, 0, 6, 0]
        panel_iy    = [0, 0, 0, 0]
        scan_tilt = 0
        plot_orient = args.orient

        # Build data dict for shared functions
        scan_data = dict(coords=coords, energies=energies, enames=enames, ix=ix, iy=iy,
                         orientxy=orientxy, orientz=orientz, zdist=zdist, mol_tag=mol_tag,
                         E_int=E_int, E0=E0, weights=weights)

        P_H0 = float(plq_H[0]); P_O0 = float(plq_O[0])

        def _plot_scan(fig_path, P_H_use, P_O_use, title_tag, HH_use=0.0, HO_use=0.0):
            panels = su.prepare_scan_panel_data(scan_data, gridff, g0, dg, panel_mols, panel_ix, panel_iy, panel_sites,
                                                 plot_orient, scan_tilt, dz_shift_fit)
            fig, axs = plt.subplots(2, 2, figsize=(12, 10))
            axs = axs.flatten()
            for pidx, panel in enumerate(panels):
                ax = axs[pidx]; axr = ax.twinx()
                if panel is None: continue
                Em_s = su.compute_model_Eint(panel, P_H_use, P_O_use, qH_fit, beta=beta_fit, H_H=HH_use, H_O=HO_use)
                Edft_s = panel['E_int_dft']
                z_s = panel['z_s']; w_s = panel['w_s']
                resid_weighted = (Em_s - Edft_s) * w_s
                rms_weighted = np.sqrt(np.mean(resid_weighted**2))
                ax.plot(z_s, Edft_s, ls=':', lw=1.5, color='k', label=f'{plot_orient} (DFT)')
                ax.plot(z_s, Em_s,   ls='-', lw=0.6, color='k', label=f'{plot_orient} ({title_tag})')
                axr.plot(z_s, resid_weighted, ls='-', lw=0.6, color='r', alpha=0.35, label=f'w*(E_model-E_DFT) RMS={rms_weighted:.3f}')
                ax.axhline(0, color='k', lw=0.5, alpha=0.5)
                axr.axhline(0, color='k', lw=0.5, alpha=0.15)
                ax.set_title(panel['title']); ax.set_xlabel('zdist [A]'); ax.set_ylabel('E_int [eV]')
                axr.set_ylabel('residual [eV]'); axr.set_ylim(-0.5, 0.5); ax.set_ylim(-0.5, 0.5)
                ax.legend(); ax.grid(True, alpha=0.3)
            cap = f"{title_tag}: P_H={P_H_use:.3f} P_O={P_O_use:.3f} H_H={HH_fit:.2f} H_O={HO_fit:.2f} q_H={qH_fit:.3f} beta={beta_fit} | Eint_max={Eint_max:.2f} kT={kT_weight:.2f}"
            fig.suptitle(cap, fontsize=10)
            plt.tight_layout(rect=(0, 0, 1, 0.96)); plt.savefig(fig_path, dpi=150); plt.close(fig)

        scan_path_def = os.path.join(out_dir, 'scan_DFT_vs_default.png')
        _plot_scan(scan_path_def, P_H0, P_O0, 'default', HH_use=0.0, HO_use=0.0)
        print('Saved 1D scan diagnostic (default):', scan_path_def)

        scan_path_fit = os.path.join(out_dir, 'scan_DFT_vs_fitted.png')
        _plot_scan(scan_path_fit, float(PH_fit), float(PO_fit), 'fitted', HH_use=float(HH_fit), HO_use=float(HO_fit))
        print('Saved 1D scan diagnostic (fitted):', scan_path_fit)

    print('\nDone. GridFF saved to:')
    print(f'  {gridff_path}')
    print(f'  {meta_path}')
    print('Diagnostic plots saved to:')
    print(f'  {out_dir}/')


if __name__ == '__main__':
    main()
