name: CMake on a single platform

on:
  push:
    branches: [ "Milan1" ]
  pull_request:
    branches: [ "Milan1" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Test
        run: |
          mkdir -p ${{ github.workspace }}/cpp/Build
          
          cmake -B${{ github.workspace }}/cpp/Build -S${{ github.workspace }}/cpp -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          
          cmake --build ${{ github.workspace }}/cpp/Build -- -j19
          
          ctest --test-dir ${{ github.workspace }}/cpp/Build --output-on-failure --verbose
