name: CMake on a single platform

on:
  push:
    branches: [ "Milan1" ]
  pull_request:
    branches: [ "Milan1" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Test
        run: |
          mkdir ${{ github.workspace }}/cpp/Build
          
          cmake ${{ github.workspace }}/cpp
          
          make ${{ github.workspace }}/cpp/Build -- -j19
          
          ctest ${{github.workspace}}/cpp/Build -V --test-dir ${{github.workspace}}/cpp/Build/tests
